[2025-04-23T00:33:06.863+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T00:33:06.867+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_stock_price.cleanup_data scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T00:33:06.870+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_stock_price.cleanup_data scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T00:33:06.870+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-23T00:33:06.873+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): cleanup_data> on 2025-04-22 00:00:00+00:00
[2025-04-23T00:33:06.877+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_stock_price', 'cleanup_data', 'scheduled__2025-04-22T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/daily_stock_price.py', '--cfg-path', '/tmp/tmpnfgo0jwb']
[2025-04-23T00:33:06.879+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T00:33:06.880+0000] {standard_task_runner.py:105} INFO - Job 177: Subtask cleanup_data
[2025-04-23T00:33:06.880+0000] {standard_task_runner.py:72} INFO - Started process 5183 to run task
[2025-04-23T00:33:06.898+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_stock_price.cleanup_data scheduled__2025-04-22T00:00:00+00:00 [running]> on host 30b8bbcaa7d3
[2025-04-23T00:33:06.926+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_stock_price' AIRFLOW_CTX_TASK_ID='cleanup_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T00:00:00+00:00'
[2025-04-23T00:33:06.926+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T00:33:06.932+0000] {connection.py:395} INFO - Snowflake Connector for Python Version: 3.8.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-23T00:33:06.932+0000] {connection.py:1235} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T00:33:07.304+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-04-23T00:33:07.771+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-04-23T00:33:07.772+0000] {logging_mixin.py:190} INFO - Successfully cleaned up old rows.
[2025-04-23T00:33:07.773+0000] {connection.py:758} INFO - closed
[2025-04-23T00:33:07.829+0000] {connection.py:764} INFO - No async queries seem to be running, deleting session
[2025-04-23T00:33:07.886+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T00:33:07.899+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T00:33:07.900+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=daily_stock_price, task_id=cleanup_data, run_id=scheduled__2025-04-22T00:00:00+00:00, execution_date=20250422T000000, start_date=20250423T003306, end_date=20250423T003307
[2025-04-23T00:33:07.919+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T00:33:07.930+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T00:33:07.930+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
